### ISSUE TITLE
rpc

### ISSUE THREAD

**Issue by mhhajeer** [intel/lmbench#1]
cd src && make
make[1]: Entering directory '/root/enabling/lmbench/src'
gmake[2]: Entering directory '/root/enabling/lmbench/src'
gcc -O -DRUSAGE -DHAVE_uint=1 -DHAVE_int64_t=1 -DHAVE_DRAND48 -DHAVE_SCHED_SETAFFINITY=1   -c lib_tcp.c -o ../bin/x86_64-linux-gnu/lib_tcp.o
In file included from lib_tcp.c:9:
bench.h:38:10: fatal error: rpc/rpc.h: No such file or directory
 #include <rpc/rpc.h>
          ^~~~~~~~~~~
compilation terminated.
gmake[2]: *** [Makefile:246: ../bin/x86_64-linux-gnu/lib_tcp.o] Error 1
gmake[2]: Leaving directory '/root/enabling/lmbench/src'
make[1]: *** [Makefile:114: lmbench] Error 2
make[1]: Leaving directory '/root/enabling/lmbench/src'
make: *** [Makefile:20: build] Error 2

**Comment by mhhajeer** [comment]
https://fedoraproject.org/wiki/Changes/SunRPCRemoval

**Comment by tuangu** [comment]
I encounter the same problem on my machine. For a quick and dirty solution to compile the code, I pulled the PR #5 and added the following in `script/build` (just before that last 2 lines).

```
LDLIBS="${LDLIBS} -ltirpc"
CFLAGS="${CFLAGS} -I/usr/include/tirpc"

# now go ahead and build everything!
${MAKE} OS="${OS}" CC="${CC}" CFLAGS="${CFLAGS}" LDLIBS="${LDLIBS}" O="${BINDIR}" $*
```
